# 站点名称
site_name: 'Network Guide'
# 仓库链接
repo_url: https://github.com/zjZSTU/network-guide.git
# 作者
site_author: 'zhujian'
# 版权信息
copyright: '2019, zhujian'
# 源文件目录
docs_dir: 'docs'
# 生成静态文件目录
site_dir: 'site'
# 额外信息
extra:
    # 版本号
    version: 2.0.0
# 主题
theme: 
    # name: 'readthedocs'
    # name: 'mkdocs'
    name: 'material'
# markdown扩展
markdown_extensions:
    - toc:
        permalink: true
    - pymdownx.arithmatex

extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
# 导航
nav:
    - Home: index.md
    - 基本概念:
        - 'IP地址': './basic/ip地址.md'
        - '路由器、交换机、集线器、中继器': './basic/路由器、交换机、集线器、中继器.md'
        - '局域网、广域网、互联网和私有专用网': './basic/局域网、广域网、互联网和私有专用网.md'
        - '网络体系结构': './basic/网络体系结构.md'
        - 'URL构成': './basic/URL构成.md'
        - 'DNS解析过程': './basic/DNS解析过程.md'
        - '[namesilo][dnspod]域名申请和解析': './basic/[namesilo][dnspod]域名申请和解析.md'
        - '[阿里云][域名解析]URL转发': './basic/[阿里云][域名解析]URL转发.md'
    - 进阶操作:
            - '[Ubuntu 18.04]wifi信息查询': './advanced/[Ubuntu 18.04]wifi信息查询.md'
            - '[Ubuntu 18.04][resolv.conf]公共DNS设置': './advanced/[Ubuntu 18.04][resolv.conf]公共DNS设置.md'
            - '[Docker][Ubuntu 18.04]网络工具安装': './advanced/[Docker][Ubuntu 18.04]网络工具安装.md'
            - '[nslookup]域名解析': './advanced/[nslookup]域名解析.md'
            - '[netstat]端口查询': './advanced/[netstat]端口查询.md'
            - '[nc]远程端口查询': './advanced/[nc]远程端口查询.md'
    - 内网穿透:
        - '前言': './intranet-penetration/前言.md'
        - '[内网穿透][路由器]虚拟服务器': './intranet-penetration/[内网穿透][路由器]虚拟服务器.md'
        - '[内网穿透]花生壳': './intranet-penetration/[内网穿透]花生壳.md'
        - '[内网穿透]n2n原理': './intranet-penetration/[内网穿透]n2n原理.md'
        - '[内网穿透]n2n实现': './intranet-penetration/[内网穿透]n2n实现.md'
    - Ngrok:
        - '引言': './intranet-penetration/ngrok/index.md'
        - '[内网穿透]ngrok实现': './intranet-penetration/ngrok/[内网穿透]ngrok实现.md'
        - '[ngrok]TCP和HTTP连接配置': './intranet-penetration/ngrok/[ngrok]TCP和HTTP连接配置.md'
        - '[ngrok]Ubuntu service实现': './intranet-penetration/ngrok/[ngrok]Ubuntu service实现.md'
        - '[ngrok]docker实现': './intranet-penetration/ngrok/[ngrok]docker实现.md'
    - 'Nginx使用':
        - '安装': './nginx/安装.md'
        - '测试': './nginx/测试.md'
        - '配置': './nginx/配置.md'
        - '中文乱码': './nginx/中文乱码.md'
        - '托管网站': './nginx/托管网站.md'
        - '[阿里云]配置HTTPs': './nginx/[阿里云]配置HTTPs.md'
        - '[腾讯云]配置HTTPs': './nginx/[腾讯云]配置HTTPs.md'
        - '多域名配置同一端口': './nginx/多域名配置同一端口.md'
        - '反向代理': './nginx/反向代理.md'
        - '[译]NGINX Reverse Proxy': './nginx/[译]NGINX Reverse Proxy.md'
        - 'docker安装nginx': './nginx/docker安装nginx.md'
        - '文件共享': './nginx/文件共享.md'
    - 'Tomcat使用':
        - '关于Tomcat': './tomcat/关于Tomcat.md'
        - '[Ubuntu 16.02]Tomcat9安装': './tomcat/[Ubuntu 16.02]Tomcat9安装.md'
        - '非root用户运行': './tomcat/非root用户运行.md'
    - 'SSH使用':
        - 'get-started':
            - 'http和ssh协议': './ssh/http和ssh协议.md'
            - '[SSH]远程连接': './ssh/[SSH]远程连接.md'
            - '[SSH]常用工具': './ssh/[SSH]常用工具.md'
            - '[SSH]生成密钥': './ssh/[SSH]生成密钥.md'
            - '[SSH]客户端配置文件config': './ssh/[SSH]客户端配置文件config.md'
        - '进阶':
            - '[SSH]禁用公钥检查': './ssh/[SSH]禁用公钥检查.md'
            - '[ssh-copy-id]复制公钥到远程服务器': './ssh/[ssh-copy-id]复制公钥到远程服务器.md'
            - '[ssh-add]添加私钥缓存': './ssh/[ssh-add]添加私钥缓存.md'
            - '[ssh-agent]代理设置': './ssh/[ssh-agent]代理设置.md'
            - '[SSH]客户端连接一段时间后卡死问题解决': './ssh/[SSH]客户端连接一段时间后卡死问题解决.md'
            - '[SSH -L]端口转发': './ssh/[SSH -L]端口转发.md'
        - '常见问题':
            - '[SSH]连接卡住': './ssh/[SSH]连接卡住.md'
            - '[SSH]Too many ssh failures': './ssh/[SSH]Too many ssh failures.md'
            - 'ssh: connect to host github.com port 22: Connection timed out': './ssh/ssh: connect to host github.com port 22: Connection timed out.md'
            - 'Bad owner or permissions on .ssh config': './ssh/Bad owner or permissions on .ssh config.md'
            - 'ssh_exchange_identification: Connection closed by remote host': './ssh/ssh_exchange_identification: Connection closed by remote host.md'
            - 'Permission denied (publickey)': './ssh/Permission denied (publickey).md'
            - '/etc/ssh/ssh_config: terminating, 1 bad configuration options': './ssh/ssh_config: terminating, 1 bad configuration options.md'